
// Objective-C API for talking to the following Go packages
//
//	github.com/centrifugal/centrifuge-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Centrifuge_FRAMEWORK_H__
#define __Centrifuge_FRAMEWORK_H__

#include "Centrifuge.objc.h"
#include "Universe.objc.h"

#endif
